;;; project-flight-logs.el -*- lexical-binding: t; -*-
;; Auto-maintained by the new-project Claude Code skill: one path per
;; scaffolded project, appended whenever a new project is created via
;; ~/Documents/project_template/init_project.sh.
(defvar my/project-flight-logs
  '("/mnt/c/Users/faadz/Projects/waterwheel_turbine_upscaling/FLIGHT_LOG.org"
    "/mnt/g/My Drive/Work/2025_2026_2/swa_akreditasi/FLIGHT_LOG.org"
    "/mnt/g/My Drive/Research/MentorGrant/lundu_publication/FLIGHT_LOG.org"
    "/mnt/c/Users/faadz/Projects/vortex_generator_paper/FLIGHT_LOG.org"
    "/home/adzlan/Projects/wastewater_to_resources/FLIGHT_LOG.org"
    "/home/adzlan/Projects/bidara_bioactive_compounds/FLIGHT_LOG.org"
    "/home/adzlan/Projects/generalised_cruciform_energy_harvester/FLIGHT_LOG.org"
    "/home/adzlan/Projects/renewable_energy_sustainability_awareness/FLIGHT_LOG.org"
    "/mnt/g/My Drive/RIEC/2026/09-TravelClaims/FLIGHT_LOG.org"
    "/home/adzlan/Projects/OpenFoam/rotary_dryer/FLIGHT_LOG.org"
    "/home/adzlan/Projects/wolfram_script_usage/FLIGHT_LOG.org"
    "/home/adzlan/Projects/OpenFoam/mobile_clothes_drying_rack/FLIGHT_LOG.org"
    "/home/adzlan/Projects/OpenFoam/emergency_floating_storage/FLIGHT_LOG.org"
    "/home/adzlan/Projects/reference_pd_thesis/FLIGHT_LOG.org"
    "/home/adzlan/Projects/pengurusan_penyelidikan_di_ppp_ipta/FLIGHT_LOG.org"
    "/home/adzlan/Projects/digital_economy_awards_2026/FLIGHT_LOG.org"
    "/mnt/c/Users/faadz/Projects/tambang_ziarah_wilayah/hari_raya_2026/FLIGHT_LOG.org"
    "/home/adzlan/Projects/teaching/2026_2027_1/masters_candidate_probal_roy/FLIGHT_LOG.org"
    "/mnt/g/My Drive/Teaching-Personal/2025_2026_2/KNJ3065/FLIGHT_LOG.org"
    "/mnt/c/Users/faadz/Projects/tambang_ziarah_wilayah/hujung_tahun_2026/FLIGHT_LOG.org"
    "/mnt/c/Users/faadz/Projects/gmail_mcp/FLIGHT_LOG.org"
    "/mnt/h/My Drive/Research-UNIMAS/my_professional_cv/FLIGHT_LOG.org"
    "/mnt/h/My Drive/RDICE/2026/17-NazimJambli/FLIGHT_LOG.org"
    "/mnt/h/My Drive/Teaching-UNIMAS/2026_2027_1/KNJ4192/FLIGHT_LOG.org"
    "/mnt/h/My Drive/Teaching-UNIMAS/2026_2027_1/KNJ4192/riverine_hydrokinetic_assessment/FLIGHT_LOG.org"
    "/home/adzlan/Projects/learn_antigravity_cli/FLIGHT_LOG.org"
    "/mnt/g/My Drive/Teaching-Personal/academicAdvicing/FLIGHT_LOG.org"
    "/mnt/c/Users/faadz/Projects/troubleshoot_windows11/FLIGHT_LOG.org"
    "/mnt/g/My Drive/Peribadi/finance/spending_tracker/FLIGHT_LOG.org"
    "/home/adzlan/Projects/fill_in_forms/FLIGHT_LOG.org"
    "/home/adzlan/Projects/training/quality_management/FLIGHT_LOG.org"))
